########################################################################################
# "yarn install" composite action for yarn 2/3/4+ and "nodeLinker: node-modules"       #
#--------------------------------------------------------------------------------------#
# Cache:                                                                               #
#   - Downloaded zip archive (multi-arch, preserved across yarn.lock changes)          #
#   - Yarn install state (discarded on yarn.lock changes)                              #
# References:                                                                          #
#   - bench: https://gist.github.com/belgattitude/0ecd26155b47e7be1be6163ecfbb0f0b     #
#   - vs @setup/node: https://github.com/actions/setup-node/issues/325                 #
########################################################################################

name: "Yarn install"
description: "Run yarn install with node_modules linker and cache enabled"
inputs:
  node_version:
    required: false
    default: v20.x

runs:
  using: "composite"
  steps:
    - name: Use Node ${{ inputs.node_version }}
      uses: buildjet/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'yarn'  # This will ensure Yarn is installed and cached
    - name: Expose yarn config as "$GITHUB_OUTPUT"
      id: yarn-config
      shell: bash
      run: |
        echo "CACHE_FOLDER=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    # Combined cache for yarn downloads, node_modules, and install state
    - name: Restore combined cache
      uses: buildjet/cache@v4
      id: yarn-combined-cache
      with:
        path: |
          ${{ steps.yarn-config.outputs.CACHE_FOLDER }}
          **/node_modules/
          .yarn/ci-cache/
        key: ${{ runner.os }}-yarn-combined-${{ hashFiles('yarn.lock') }}

    - name: Install dependencies and generate Prisma
      shell: bash
      run: |
        yarn install --inline-builds
        yarn prisma generate
      env:
        # CI optimizations. Overrides yarnrc.yml options (or their defaults) in the CI action.
        YARN_ENABLE_IMMUTABLE_INSTALLS: "false" # So it doesn't try to remove our private submodule deps
        YARN_ENABLE_GLOBAL_CACHE: "false" # Use local cache folder to keep downloaded archives
        YARN_INSTALL_STATE_PATH: .yarn/ci-cache/install-state.gz # Very small speedup when lock does not change
        YARN_NM_MODE: "hardlinks-local" # Reduce node_modules size
        # Other environment variables
        HUSKY: "0" # By default do not run HUSKY install
