name: Cache Database
description: Cache the database for faster CI runs
inputs:
  DATABASE_URL:
    required: true
    description: "Database URL"
  DATABASE_DIRECT_URL:
    required: true
    description: "Direct database URL"
  E2E_TEST_CALCOM_QA_EMAIL:
    required: false
    description: "E2E test Cal.com QA email"
  E2E_TEST_CALCOM_QA_PASSWORD:
    required: false
    description: "E2E test Cal.com QA password"
  E2E_TEST_CALCOM_QA_GCAL_CREDENTIALS:
    required: false
    description: "E2E test Cal.com QA GCal credentials"
  E2E_TEST_CALCOM_GCAL_KEYS:
    required: false
    description: "E2E test Cal.com GCal keys"
outputs:
  cache-hit:
    description: "Whether the cache was hit"
    value: ${{ steps.cache-db.outputs.cache-hit }}
runs:
  using: "composite"
  steps:
    - name: Install PostgreSQL client tools
      shell: bash
      run: |
        apt-get update
        apt-get install -y postgresql-client
    - name: Cache Database
      id: cache-db
      uses: buildjet/cache@v4
      env:
        cache-name: db
        key-1: ${{ hashFiles('prisma/schema.prisma') }}
        key-2: ${{ hashFiles('prisma/migrations/**/*.sql') }}
        key-3: ${{ github.event.pull_request.number || github.ref }}
        # Ensures cache-db.yml will always be fresh
        key-4: ${{ github.sha }}
      with:
        path: |
          .cache/db
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.key-1 }}-${{ env.key-2 }}-${{ env.key-3 }}-${{ env.key-4 }}
    - name: Log Cache Hit
      if: steps.cache-db.outputs.cache-hit == 'true'
      run: echo "Cache hit for database. Skipping database setup."
    - name: Setup Database
      if: steps.cache-db.outputs.cache-hit != 'true'
      run: |
        mkdir -p .cache/db
        yarn prisma migrate deploy
        pg_dump ${{ inputs.DATABASE_URL }} > .cache/db/dump.sql
        if [ -n "${{ inputs.E2E_TEST_CALCOM_QA_EMAIL }}" ]; then
          echo "E2E_TEST_CALCOM_QA_EMAIL=${{ inputs.E2E_TEST_CALCOM_QA_EMAIL }}" >> .cache/db/env
        fi
        if [ -n "${{ inputs.E2E_TEST_CALCOM_QA_PASSWORD }}" ]; then
          echo "E2E_TEST_CALCOM_QA_PASSWORD=${{ inputs.E2E_TEST_CALCOM_QA_PASSWORD }}" >> .cache/db/env
        fi
        if [ -n "${{ inputs.E2E_TEST_CALCOM_QA_GCAL_CREDENTIALS }}" ]; then
          echo "E2E_TEST_CALCOM_QA_GCAL_CREDENTIALS=${{ inputs.E2E_TEST_CALCOM_QA_GCAL_CREDENTIALS }}" >> .cache/db/env
        fi
        if [ -n "${{ inputs.E2E_TEST_CALCOM_GCAL_KEYS }}" ]; then
          echo "E2E_TEST_CALCOM_GCAL_KEYS=${{ inputs.E2E_TEST_CALCOM_GCAL_KEYS }}" >> .cache/db/env
        fi
