name: Cache Database
description: Cache the database for faster CI runs
inputs:
  E2E_TEST_CALCOM_QA_EMAIL:
    required: false
    description: "E2E test Cal.com QA email"
  E2E_TEST_CALCOM_QA_PASSWORD:
    required: false
    description: "E2E test Cal.com QA password"
  E2E_TEST_CALCOM_QA_GCAL_CREDENTIALS:
    required: false
    description: "E2E test Cal.com QA GCal credentials"
  E2E_TEST_CALCOM_GCAL_KEYS:
    required: false
    description: "E2E test Cal.com GCal keys"
outputs:
  cache-hit:
    description: "Whether the cache was hit"
    value: ${{ steps.cache-db.outputs.cache-hit }}
runs:
  using: "composite"
  steps:
    - name: Cache Database
      id: cache-db
      uses: buildjet/cache@v4
      env:
        cache-name: db-v1
      with:
        path: |
          .cache/db
        key: ${{ env.cache-name }}-${{ hashFiles('packages/prisma/schema.prisma') }}-${{ hashFiles('packages/prisma/migrations/**/*.sql') }}
        restore-keys: |
          ${{ env.cache-name }}-${{ hashFiles('packages/prisma/schema.prisma') }}-
          ${{ env.cache-name }}-

    - name: Setup Database
      if: steps.cache-db.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p .cache/db
        # Run migrations
        yarn prisma migrate deploy
        # Run seeds
        yarn prisma db seed
        # Create optimized dump with custom format and compression
        PGPASSWORD=postgres pg_dump -Fc -Z9 -h localhost -p 5432 -U postgres -d calendso > .cache/db/dump.fc
        # Store test credentials if provided
        if [ -n "${{ inputs.E2E_TEST_CALCOM_QA_EMAIL }}" ]; then
          echo "E2E_TEST_CALCOM_QA_EMAIL=${{ inputs.E2E_TEST_CALCOM_QA_EMAIL }}" >> .cache/db/env
        fi
        if [ -n "${{ inputs.E2E_TEST_CALCOM_QA_PASSWORD }}" ]; then
          echo "E2E_TEST_CALCOM_QA_PASSWORD=${{ inputs.E2E_TEST_CALCOM_QA_PASSWORD }}" >> .cache/db/env
        fi
        if [ -n "${{ inputs.E2E_TEST_CALCOM_QA_GCAL_CREDENTIALS }}" ]; then
          echo "E2E_TEST_CALCOM_QA_GCAL_CREDENTIALS=${{ inputs.E2E_TEST_CALCOM_QA_GCAL_CREDENTIALS }}" >> .cache/db/env
        fi
        if [ -n "${{ inputs.E2E_TEST_CALCOM_GCAL_KEYS }}" ]; then
          echo "E2E_TEST_CALCOM_GCAL_KEYS=${{ inputs.E2E_TEST_CALCOM_GCAL_KEYS }}" >> .cache/db/env
        fi

    - name: Restore Database
      if: steps.cache-db.outputs.cache-hit == 'true'
      shell: bash
      run: |
        # Drop existing DB
        PGPASSWORD=postgres psql -h localhost -p 5432 -U postgres -c "DROP DATABASE IF EXISTS calendso"
        PGPASSWORD=postgres psql -h localhost -p 5432 -U postgres -c "CREATE DATABASE calendso"
        # Fast parallel restore
        PGPASSWORD=postgres pg_restore -j 4 -h localhost -p 5432 -U postgres -d calendso .cache/db/dump.fc
        # Restore test credentials if they exist
        if [ -f ".cache/db/env" ]; then
          while IFS= read -r line; do
            export "$line"
          done < .cache/db/env
        fi
